# Generated by Django 3.2.8 on 2021-10-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True)),
                ('accused_description', models.CharField(blank=True, max_length=1000)),
                ('repeat', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('event_description', models.CharField(blank=True, max_length=4000)),
                ('accused_relationship', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('client', 'Client'), ('boss', 'Boss'), ('other', 'Other')], max_length=100)),
                ('submitter_relationship', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('client', 'Client'), ('boss', 'Boss'), ('other', 'Other')], max_length=100)),
            ],
        ),
    ]
