# Generated by Django 3.2.3 on 2021-10-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_organisation_city'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.organisation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
