# Generated by Django 3.2.8 on 2021-10-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AddField(
            model_name='report',
            name='event_description',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='report',
            name='accused_relationship',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('client', 'Client'), ('boss', 'Boss'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='submitter_relationship',
            field=models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('client', 'Client'), ('boss', 'Boss'), ('other', 'Other')], max_length=100),
        ),
    ]
