# Generated by Django 3.2.8 on 2021-10-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='city',
            field=models.CharField(choices=[('edinburgh', 'Edinburgh')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='country',
            field=models.CharField(choices=[('great_britain', 'Great Britain'), ('ireland', 'Ireland')], max_length=50),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='type',
            field=models.CharField(choices=[('pubbar', 'Pub/Bar'), ('club', 'Nightclub'), ('society', 'University Society'), ('school', 'School'), ('office', 'Office'), ('store', 'Store'), ('other', 'Other')], max_length=25),
        ),
    ]
