# Generated by Django 3.2.3 on 2021-10-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20211016_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='active',
        ),
    ]
